In [8]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import random

In [2]:
arr_3 = np.array([1, 2, 3, 4])
arr_4 = np.array([2, 4, 6, 8])

In [3]:
arr_3 + arr_4

array([ 3,  6,  9, 12])

In [4]:
arr_3 - arr_4

array([-1, -2, -3, -4])

In [5]:
arr_3 * arr_4

array([ 2,  8, 18, 32])

In [6]:
arr_3 / arr_4

array([0.5, 0.5, 0.5, 0.5])

In [9]:
arr_5 = random.randint(100, size=(4))

In [10]:
arr_5

array([92, 67, 19, 29])

In [11]:
arr_6 = random.randint(100, size=(2, 3))

In [12]:
arr_6

array([[32, 47, 18],
       [94, 32, 64]])

In [13]:
random.rand(4)

array([0.78799359, 0.83147808, 0.56345587, 0.67205887])

In [14]:
random.choice(arr_3)

4

In [15]:
arr_3.sum()

10

In [16]:
print(arr_6)

[[32 47 18]
 [94 32 64]]


In [17]:
arr_6.sum(axis=0)

array([126,  79,  82])

In [18]:
arr_6.cumsum(axis=1)

array([[ 32,  79,  97],
       [ 94, 126, 190]], dtype=int32)

In [19]:
arr_6.min(axis=1)

array([18, 32])

In [20]:
arr_6.max(axis=0)

array([94, 47, 64])

In [21]:
print("arr_3", arr_3)

arr_3 [1 2 3 4]


In [22]:
print("arr_4", arr_4)

arr_4 [2 4 6 8]


In [23]:
np.add(arr_3, 5)

array([6, 7, 8, 9])

In [24]:
np.add(arr_3, arr_4)

array([ 3,  6,  9, 12])

In [25]:
np.subtract(arr_3, arr_4)

array([-1, -2, -3, -4])

In [26]:
np.multiply(arr_3, arr_4)

array([ 2,  8, 18, 32])

In [27]:
np.divide(arr_3, arr_4)

array([0.5, 0.5, 0.5, 0.5])

In [28]:
arr_5 = np.array([[1, 2], [3, 4]])

In [29]:
arr_6 = np.array([[2, 4], [6, 9]])

In [30]:
print("arr_5\n", arr_5)

arr_5
 [[1 2]
 [3 4]]


In [31]:
print("arr_6\n", arr_6)

arr_6
 [[2 4]
 [6 9]]


In [32]:
np.remainder(arr_6, arr_5)

array([[0, 0],
       [0, 1]], dtype=int32)

In [33]:
np.power(arr_6, arr_5)

array([[   2,   16],
       [ 216, 6561]], dtype=int32)

In [34]:
np.sqrt(arr_3)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [35]:
np.cbrt(arr_3)

array([1.        , 1.25992105, 1.44224957, 1.58740105])

In [36]:
np.absolute([-1, -2])

array([1, 2])

In [37]:
np.exp(arr_3)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [38]:
np.log(arr_3)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [39]:
np.log2(arr_3)

array([0.       , 1.       , 1.5849625, 2.       ])

In [40]:
np.log10(arr_3)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [41]:
np.gcd.reduce([9, 12, 15])

3

In [42]:
np.lcm.reduce([9, 12, 15])

180

In [43]:
np.floor([1.2, 2.5])

array([1., 2.])

In [44]:
np.ceil([1.2, 2.5])

array([2., 3.])

In [45]:
sq_arr = np.arange(6)**2

In [46]:
sq_arr[arr_3]

array([ 1,  4,  9, 16], dtype=int32)

In [47]:
arr_7 = random.randint(100, size=(5, 3))

In [48]:
print("arr_7\n", arr_7)

arr_7
 [[35 55 68]
 [18 63 88]
 [85 31 83]
 [49 76  7]
 [89 15 30]]


In [49]:
mc_index = arr_7.argmax(axis=0)

In [50]:
mc_index

array([4, 3, 1], dtype=int64)

In [51]:
max_nums = arr_7[mc_index]

In [52]:
arr_7[mc_index, range(arr_7.shape[1])]

array([89, 76, 88])